apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm
  namespace: openshift-sandboxed-containers-operator
data:
  CLOUD_PROVIDER: "aws"
  VXLAN_PORT: "9000"
  PROXY_TIMEOUT: "8m"
  PODVM_INSTANCE_TYPE: "t3.medium"
  PODVM_INSTANCE_TYPES: "t2.small,t2.medium,t3.large"
  PODVM_AMI_ID: ""
  AWS_REGION: ""
  AWS_SUBNET_ID: ""
  AWS_VPC_ID: ""
  AWS_SG_IDS: ""
  TAGS: ""
  PEERPODS_LIMIT_PER_NODE: "10"
  ROOT_VOLUME_SIZE: "6"
  DISABLECVM: "true"
